// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Category.proto

package grpc;

public final class Category {
  private Category() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CategoryServerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CategoryServerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code CategoryServerResponse}
   */
  public  static final class CategoryServerResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CategoryServerResponse)
      CategoryServerResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CategoryServerResponse.newBuilder() to construct.
    private CategoryServerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryServerResponse() {
      code_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CategoryServerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Category.internal_static_CategoryServerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Category.internal_static_CategoryServerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Category.CategoryServerResponse.class, grpc.Category.CategoryServerResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Category.CategoryServerResponse)) {
        return super.equals(obj);
      }
      grpc.Category.CategoryServerResponse other = (grpc.Category.CategoryServerResponse) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Category.CategoryServerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryServerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryServerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryServerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Category.CategoryServerResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CategoryServerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CategoryServerResponse)
        grpc.Category.CategoryServerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Category.internal_static_CategoryServerResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Category.internal_static_CategoryServerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Category.CategoryServerResponse.class, grpc.Category.CategoryServerResponse.Builder.class);
      }

      // Construct using grpc.Category.CategoryServerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Category.internal_static_CategoryServerResponse_descriptor;
      }

      @java.lang.Override
      public grpc.Category.CategoryServerResponse getDefaultInstanceForType() {
        return grpc.Category.CategoryServerResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Category.CategoryServerResponse build() {
        grpc.Category.CategoryServerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Category.CategoryServerResponse buildPartial() {
        grpc.Category.CategoryServerResponse result = new grpc.Category.CategoryServerResponse(this);
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Category.CategoryServerResponse) {
          return mergeFrom((grpc.Category.CategoryServerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Category.CategoryServerResponse other) {
        if (other == grpc.Category.CategoryServerResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Category.CategoryServerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Category.CategoryServerResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CategoryServerResponse)
    }

    // @@protoc_insertion_point(class_scope:CategoryServerResponse)
    private static final grpc.Category.CategoryServerResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Category.CategoryServerResponse();
    }

    public static grpc.Category.CategoryServerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryServerResponse>
        PARSER = new com.google.protobuf.AbstractParser<CategoryServerResponse>() {
      @java.lang.Override
      public CategoryServerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CategoryServerResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryServerResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryServerResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Category.CategoryServerResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CategoryDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idCategory = 1;</code>
     */
    int getIdCategory();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code CategoryDTO}
   */
  public  static final class CategoryDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CategoryDTO)
      CategoryDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CategoryDTO.newBuilder() to construct.
    private CategoryDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryDTO() {
      idCategory_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CategoryDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idCategory_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Category.internal_static_CategoryDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Category.internal_static_CategoryDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Category.CategoryDTO.class, grpc.Category.CategoryDTO.Builder.class);
    }

    public static final int IDCATEGORY_FIELD_NUMBER = 1;
    private int idCategory_;
    /**
     * <code>int32 idCategory = 1;</code>
     */
    public int getIdCategory() {
      return idCategory_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idCategory_ != 0) {
        output.writeInt32(1, idCategory_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idCategory_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idCategory_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Category.CategoryDTO)) {
        return super.equals(obj);
      }
      grpc.Category.CategoryDTO other = (grpc.Category.CategoryDTO) obj;

      boolean result = true;
      result = result && (getIdCategory()
          == other.getIdCategory());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getIdCategory();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Category.CategoryDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Category.CategoryDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CategoryDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CategoryDTO)
        grpc.Category.CategoryDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Category.internal_static_CategoryDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Category.internal_static_CategoryDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Category.CategoryDTO.class, grpc.Category.CategoryDTO.Builder.class);
      }

      // Construct using grpc.Category.CategoryDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idCategory_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Category.internal_static_CategoryDTO_descriptor;
      }

      @java.lang.Override
      public grpc.Category.CategoryDTO getDefaultInstanceForType() {
        return grpc.Category.CategoryDTO.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Category.CategoryDTO build() {
        grpc.Category.CategoryDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Category.CategoryDTO buildPartial() {
        grpc.Category.CategoryDTO result = new grpc.Category.CategoryDTO(this);
        result.idCategory_ = idCategory_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Category.CategoryDTO) {
          return mergeFrom((grpc.Category.CategoryDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Category.CategoryDTO other) {
        if (other == grpc.Category.CategoryDTO.getDefaultInstance()) return this;
        if (other.getIdCategory() != 0) {
          setIdCategory(other.getIdCategory());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Category.CategoryDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Category.CategoryDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idCategory_ ;
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public int getIdCategory() {
        return idCategory_;
      }
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public Builder setIdCategory(int value) {
        
        idCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public Builder clearIdCategory() {
        
        idCategory_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CategoryDTO)
    }

    // @@protoc_insertion_point(class_scope:CategoryDTO)
    private static final grpc.Category.CategoryDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Category.CategoryDTO();
    }

    public static grpc.Category.CategoryDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryDTO>
        PARSER = new com.google.protobuf.AbstractParser<CategoryDTO>() {
      @java.lang.Override
      public CategoryDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CategoryDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Category.CategoryDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryObjDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CategoryObjDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    boolean hasCategory();
    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    grpc.Category.CategoryDTO getCategory();
    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    grpc.Category.CategoryDTOOrBuilder getCategoryOrBuilder();

    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    boolean hasServerResponse();
    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    grpc.Category.CategoryServerResponse getServerResponse();
    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    grpc.Category.CategoryServerResponseOrBuilder getServerResponseOrBuilder();
  }
  /**
   * Protobuf type {@code CategoryObjDTO}
   */
  public  static final class CategoryObjDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CategoryObjDTO)
      CategoryObjDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CategoryObjDTO.newBuilder() to construct.
    private CategoryObjDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryObjDTO() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CategoryObjDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grpc.Category.CategoryDTO.Builder subBuilder = null;
              if (category_ != null) {
                subBuilder = category_.toBuilder();
              }
              category_ = input.readMessage(grpc.Category.CategoryDTO.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(category_);
                category_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              grpc.Category.CategoryServerResponse.Builder subBuilder = null;
              if (serverResponse_ != null) {
                subBuilder = serverResponse_.toBuilder();
              }
              serverResponse_ = input.readMessage(grpc.Category.CategoryServerResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverResponse_);
                serverResponse_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Category.internal_static_CategoryObjDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Category.internal_static_CategoryObjDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Category.CategoryObjDTO.class, grpc.Category.CategoryObjDTO.Builder.class);
    }

    public static final int CATEGORY_FIELD_NUMBER = 1;
    private grpc.Category.CategoryDTO category_;
    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    public boolean hasCategory() {
      return category_ != null;
    }
    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    public grpc.Category.CategoryDTO getCategory() {
      return category_ == null ? grpc.Category.CategoryDTO.getDefaultInstance() : category_;
    }
    /**
     * <code>.CategoryDTO category = 1;</code>
     */
    public grpc.Category.CategoryDTOOrBuilder getCategoryOrBuilder() {
      return getCategory();
    }

    public static final int SERVERRESPONSE_FIELD_NUMBER = 2;
    private grpc.Category.CategoryServerResponse serverResponse_;
    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    public boolean hasServerResponse() {
      return serverResponse_ != null;
    }
    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    public grpc.Category.CategoryServerResponse getServerResponse() {
      return serverResponse_ == null ? grpc.Category.CategoryServerResponse.getDefaultInstance() : serverResponse_;
    }
    /**
     * <code>.CategoryServerResponse serverResponse = 2;</code>
     */
    public grpc.Category.CategoryServerResponseOrBuilder getServerResponseOrBuilder() {
      return getServerResponse();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (category_ != null) {
        output.writeMessage(1, getCategory());
      }
      if (serverResponse_ != null) {
        output.writeMessage(2, getServerResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (category_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCategory());
      }
      if (serverResponse_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getServerResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Category.CategoryObjDTO)) {
        return super.equals(obj);
      }
      grpc.Category.CategoryObjDTO other = (grpc.Category.CategoryObjDTO) obj;

      boolean result = true;
      result = result && (hasCategory() == other.hasCategory());
      if (hasCategory()) {
        result = result && getCategory()
            .equals(other.getCategory());
      }
      result = result && (hasServerResponse() == other.hasServerResponse());
      if (hasServerResponse()) {
        result = result && getServerResponse()
            .equals(other.getServerResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCategory()) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getCategory().hashCode();
      }
      if (hasServerResponse()) {
        hash = (37 * hash) + SERVERRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getServerResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Category.CategoryObjDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryObjDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryObjDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.CategoryObjDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Category.CategoryObjDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CategoryObjDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CategoryObjDTO)
        grpc.Category.CategoryObjDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Category.internal_static_CategoryObjDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Category.internal_static_CategoryObjDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Category.CategoryObjDTO.class, grpc.Category.CategoryObjDTO.Builder.class);
      }

      // Construct using grpc.Category.CategoryObjDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (categoryBuilder_ == null) {
          category_ = null;
        } else {
          category_ = null;
          categoryBuilder_ = null;
        }
        if (serverResponseBuilder_ == null) {
          serverResponse_ = null;
        } else {
          serverResponse_ = null;
          serverResponseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Category.internal_static_CategoryObjDTO_descriptor;
      }

      @java.lang.Override
      public grpc.Category.CategoryObjDTO getDefaultInstanceForType() {
        return grpc.Category.CategoryObjDTO.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Category.CategoryObjDTO build() {
        grpc.Category.CategoryObjDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Category.CategoryObjDTO buildPartial() {
        grpc.Category.CategoryObjDTO result = new grpc.Category.CategoryObjDTO(this);
        if (categoryBuilder_ == null) {
          result.category_ = category_;
        } else {
          result.category_ = categoryBuilder_.build();
        }
        if (serverResponseBuilder_ == null) {
          result.serverResponse_ = serverResponse_;
        } else {
          result.serverResponse_ = serverResponseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Category.CategoryObjDTO) {
          return mergeFrom((grpc.Category.CategoryObjDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Category.CategoryObjDTO other) {
        if (other == grpc.Category.CategoryObjDTO.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          mergeCategory(other.getCategory());
        }
        if (other.hasServerResponse()) {
          mergeServerResponse(other.getServerResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Category.CategoryObjDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Category.CategoryObjDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private grpc.Category.CategoryDTO category_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.Category.CategoryDTO, grpc.Category.CategoryDTO.Builder, grpc.Category.CategoryDTOOrBuilder> categoryBuilder_;
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public boolean hasCategory() {
        return categoryBuilder_ != null || category_ != null;
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public grpc.Category.CategoryDTO getCategory() {
        if (categoryBuilder_ == null) {
          return category_ == null ? grpc.Category.CategoryDTO.getDefaultInstance() : category_;
        } else {
          return categoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public Builder setCategory(grpc.Category.CategoryDTO value) {
        if (categoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          category_ = value;
          onChanged();
        } else {
          categoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public Builder setCategory(
          grpc.Category.CategoryDTO.Builder builderForValue) {
        if (categoryBuilder_ == null) {
          category_ = builderForValue.build();
          onChanged();
        } else {
          categoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public Builder mergeCategory(grpc.Category.CategoryDTO value) {
        if (categoryBuilder_ == null) {
          if (category_ != null) {
            category_ =
              grpc.Category.CategoryDTO.newBuilder(category_).mergeFrom(value).buildPartial();
          } else {
            category_ = value;
          }
          onChanged();
        } else {
          categoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public Builder clearCategory() {
        if (categoryBuilder_ == null) {
          category_ = null;
          onChanged();
        } else {
          category_ = null;
          categoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public grpc.Category.CategoryDTO.Builder getCategoryBuilder() {
        
        onChanged();
        return getCategoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      public grpc.Category.CategoryDTOOrBuilder getCategoryOrBuilder() {
        if (categoryBuilder_ != null) {
          return categoryBuilder_.getMessageOrBuilder();
        } else {
          return category_ == null ?
              grpc.Category.CategoryDTO.getDefaultInstance() : category_;
        }
      }
      /**
       * <code>.CategoryDTO category = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.Category.CategoryDTO, grpc.Category.CategoryDTO.Builder, grpc.Category.CategoryDTOOrBuilder> 
          getCategoryFieldBuilder() {
        if (categoryBuilder_ == null) {
          categoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc.Category.CategoryDTO, grpc.Category.CategoryDTO.Builder, grpc.Category.CategoryDTOOrBuilder>(
                  getCategory(),
                  getParentForChildren(),
                  isClean());
          category_ = null;
        }
        return categoryBuilder_;
      }

      private grpc.Category.CategoryServerResponse serverResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.Category.CategoryServerResponse, grpc.Category.CategoryServerResponse.Builder, grpc.Category.CategoryServerResponseOrBuilder> serverResponseBuilder_;
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public boolean hasServerResponse() {
        return serverResponseBuilder_ != null || serverResponse_ != null;
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public grpc.Category.CategoryServerResponse getServerResponse() {
        if (serverResponseBuilder_ == null) {
          return serverResponse_ == null ? grpc.Category.CategoryServerResponse.getDefaultInstance() : serverResponse_;
        } else {
          return serverResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public Builder setServerResponse(grpc.Category.CategoryServerResponse value) {
        if (serverResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverResponse_ = value;
          onChanged();
        } else {
          serverResponseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public Builder setServerResponse(
          grpc.Category.CategoryServerResponse.Builder builderForValue) {
        if (serverResponseBuilder_ == null) {
          serverResponse_ = builderForValue.build();
          onChanged();
        } else {
          serverResponseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public Builder mergeServerResponse(grpc.Category.CategoryServerResponse value) {
        if (serverResponseBuilder_ == null) {
          if (serverResponse_ != null) {
            serverResponse_ =
              grpc.Category.CategoryServerResponse.newBuilder(serverResponse_).mergeFrom(value).buildPartial();
          } else {
            serverResponse_ = value;
          }
          onChanged();
        } else {
          serverResponseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public Builder clearServerResponse() {
        if (serverResponseBuilder_ == null) {
          serverResponse_ = null;
          onChanged();
        } else {
          serverResponse_ = null;
          serverResponseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public grpc.Category.CategoryServerResponse.Builder getServerResponseBuilder() {
        
        onChanged();
        return getServerResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      public grpc.Category.CategoryServerResponseOrBuilder getServerResponseOrBuilder() {
        if (serverResponseBuilder_ != null) {
          return serverResponseBuilder_.getMessageOrBuilder();
        } else {
          return serverResponse_ == null ?
              grpc.Category.CategoryServerResponse.getDefaultInstance() : serverResponse_;
        }
      }
      /**
       * <code>.CategoryServerResponse serverResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.Category.CategoryServerResponse, grpc.Category.CategoryServerResponse.Builder, grpc.Category.CategoryServerResponseOrBuilder> 
          getServerResponseFieldBuilder() {
        if (serverResponseBuilder_ == null) {
          serverResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc.Category.CategoryServerResponse, grpc.Category.CategoryServerResponse.Builder, grpc.Category.CategoryServerResponseOrBuilder>(
                  getServerResponse(),
                  getParentForChildren(),
                  isClean());
          serverResponse_ = null;
        }
        return serverResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CategoryObjDTO)
    }

    // @@protoc_insertion_point(class_scope:CategoryObjDTO)
    private static final grpc.Category.CategoryObjDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Category.CategoryObjDTO();
    }

    public static grpc.Category.CategoryObjDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryObjDTO>
        PARSER = new com.google.protobuf.AbstractParser<CategoryObjDTO>() {
      @java.lang.Override
      public CategoryObjDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CategoryObjDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryObjDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryObjDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Category.CategoryObjDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCategoryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCategoryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idCategory = 1;</code>
     */
    int getIdCategory();
  }
  /**
   * Protobuf type {@code GetCategoryRequest}
   */
  public  static final class GetCategoryRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCategoryRequest)
      GetCategoryRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCategoryRequest.newBuilder() to construct.
    private GetCategoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCategoryRequest() {
      idCategory_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCategoryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idCategory_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Category.internal_static_GetCategoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Category.internal_static_GetCategoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Category.GetCategoryRequest.class, grpc.Category.GetCategoryRequest.Builder.class);
    }

    public static final int IDCATEGORY_FIELD_NUMBER = 1;
    private int idCategory_;
    /**
     * <code>int32 idCategory = 1;</code>
     */
    public int getIdCategory() {
      return idCategory_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idCategory_ != 0) {
        output.writeInt32(1, idCategory_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idCategory_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idCategory_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Category.GetCategoryRequest)) {
        return super.equals(obj);
      }
      grpc.Category.GetCategoryRequest other = (grpc.Category.GetCategoryRequest) obj;

      boolean result = true;
      result = result && (getIdCategory()
          == other.getIdCategory());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getIdCategory();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Category.GetCategoryRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.GetCategoryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Category.GetCategoryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Category.GetCategoryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Category.GetCategoryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCategoryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCategoryRequest)
        grpc.Category.GetCategoryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Category.internal_static_GetCategoryRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Category.internal_static_GetCategoryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Category.GetCategoryRequest.class, grpc.Category.GetCategoryRequest.Builder.class);
      }

      // Construct using grpc.Category.GetCategoryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idCategory_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Category.internal_static_GetCategoryRequest_descriptor;
      }

      @java.lang.Override
      public grpc.Category.GetCategoryRequest getDefaultInstanceForType() {
        return grpc.Category.GetCategoryRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.Category.GetCategoryRequest build() {
        grpc.Category.GetCategoryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.Category.GetCategoryRequest buildPartial() {
        grpc.Category.GetCategoryRequest result = new grpc.Category.GetCategoryRequest(this);
        result.idCategory_ = idCategory_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Category.GetCategoryRequest) {
          return mergeFrom((grpc.Category.GetCategoryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Category.GetCategoryRequest other) {
        if (other == grpc.Category.GetCategoryRequest.getDefaultInstance()) return this;
        if (other.getIdCategory() != 0) {
          setIdCategory(other.getIdCategory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Category.GetCategoryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Category.GetCategoryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idCategory_ ;
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public int getIdCategory() {
        return idCategory_;
      }
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public Builder setIdCategory(int value) {
        
        idCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idCategory = 1;</code>
       */
      public Builder clearIdCategory() {
        
        idCategory_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCategoryRequest)
    }

    // @@protoc_insertion_point(class_scope:GetCategoryRequest)
    private static final grpc.Category.GetCategoryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Category.GetCategoryRequest();
    }

    public static grpc.Category.GetCategoryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCategoryRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetCategoryRequest>() {
      @java.lang.Override
      public GetCategoryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCategoryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCategoryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCategoryRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.Category.GetCategoryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryServerResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryServerResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryObjDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryObjDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCategoryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCategoryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Category.proto\"3\n\026CategoryServerRespon" +
      "se\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\"/\n\013Categor" +
      "yDTO\022\022\n\nidCategory\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"a" +
      "\n\016CategoryObjDTO\022\036\n\010category\030\001 \001(\0132\014.Cat" +
      "egoryDTO\022/\n\016serverResponse\030\002 \001(\0132\027.Categ" +
      "oryServerResponse\"(\n\022GetCategoryRequest\022" +
      "\022\n\nidCategory\030\001 \001(\0052w\n\022CategoryControlle" +
      "r\022,\n\013addCategory\022\014.CategoryDTO\032\017.Categor" +
      "yObjDTO\0223\n\013getCategory\022\023.GetCategoryRequ" +
      "est\032\017.CategoryObjDTOB\006\n\004grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CategoryServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CategoryServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryServerResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_CategoryDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CategoryDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryDTO_descriptor,
        new java.lang.String[] { "IdCategory", "Name", });
    internal_static_CategoryObjDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CategoryObjDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryObjDTO_descriptor,
        new java.lang.String[] { "Category", "ServerResponse", });
    internal_static_GetCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCategoryRequest_descriptor,
        new java.lang.String[] { "IdCategory", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
